### ISSUE TITLE
Problem parsing class names that include a space in their name

### ISSUE THREAD

**Issue by jule64** [zweifisch/enlive#1]
Hi, I don't know if it is a problem with the underlying html lib or not but I am not able to query elements on class name where the class has a space in its name:

example html:
`<td class='comment detail'>blabla</td>`

I tried the followings without success:

`(enlive-query (enlive-parse "<td class='comment detail'>blabla</td>") [.comment\ detail])`
> nil

`(enlive-query (enlive-parse "<td class='comment detail'>blabla</td>") [.\'comment\ detail\'])`
> nil

Is there a workaround or a way to fix?

**Comment by zweifisch** [comment]
hi @jule64 , this is an element with two class names, you cloud use `[.comment]` or `[.detail]` or `[.comment.detail]` which requires both classes to be presented

**Comment by jule64** [comment]
thanks a lot
